### PR TITLE
Fix the issue where the websocket no longer automatically returns the new status when the device has not been updated for a long time in cloud mode.

### PR DESCRIPTION
**Pull request by LOVE2CMOL**
```
https://coolkit-technologies.github.io/eWeLink-API/#/en/APICenterV2?id=websocket-handshake
Obtain the persistent connection address to be connected from [HTTP: Dispatchservice], 
and concatenate it into: "wss://IP:port/api/ws", so as to establish a persistent connection. After the handshake is successful, 
you need to send the string "ping" to the server periodically (see the hbInterval field for the interval) to keep the heartbeat, 
otherwise the device will be forced to go offline by the server.
```

heartbeat=90 may cause the frequency of aiohttp's automatic sending of Ping messages to change, 
which may affect the stability of the WebSocket connection. 
It is recommended to still use a boolean value to enable or disable heartbeat messages when setting the heartbeat parameter, or to use the PingPong heartbeat manager to customize the heartbeat interval time.

This PR does not conflict with [#1116](https://github.com/AlexxIT/SonoffLAN/pull/1116).

### CODE REVIEW

**Comment by AlexxIT** [comment]
Where you get all this info? `heartbeat` can't be boolean value.
And why heartbeat 90 may affect stability?

**Comment by AlexxIT** [comment]
If the ewelink servers are unstable because of a little frequent ping messages, they are very bad servers.
And there's no point in fixing them or using them at all.

**Comment by LOVE2CMOL** [comment]
Yes, I also think that their server implementation is not very good, to the point that if we don't follow the rules for pinging, they assume that we are offline.
If the documentation mentions it, then we should definitely try to optimize it. Even if the server implementation is not very good, we should still try to follow the rules as closely as possible and make adjustments where necessary to ensure that our application runs smoothly and efficiently.😀😀

**Comment by LOVE2CMOL** [comment]
Just to mention, this phenomenon generally occurs in things like switches and access control systems that do not update their status frequently. However, if your account has devices such as thermometers that update their status frequently, the cloud service can still remain updated and function properly.

**Pull request closed without merging**
