### PR TITLE
Add pre-commit and CI workflow

### PR DESCRIPTION
**Pull request by basnijholt**
This fixes the inconsistent style use and removed the `import *` imports.

It adds
* pre-commit with linters and stylers (same as in Home Assistant Core)
* GitHub Actions CI that runs pre-commit

### CODE REVIEW

**Comment by AlexxIT** [comment]
Thanks. Can you point to docs with decisions about `"--max-line-length=88", "--extend-ignore=E203,W503"` ?
I'm still using PEP8 with 79 chars. I think 9 chars more is not a big problem. But it will have to be changed in the IDE and all my projects.

**Comment by basnijholt** [comment]
The 88 char limit is from black and is the standard that was agreed on. The flake8 settings are to be compatible with black, see https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#configuration

BTW, by just running 'pre-commit install' in your repo once, these checks will automatically be performed 😄

**Comment by AlexxIT** [comment]
Will it break any pull requests with wrong style? Or just for the moment I take them in?

I don't mind, pull quests with the wrong style. It's hard for people to follow standards they don't know. I can fix all the formatting errors myself using the IDE. Not everyone uses the right IDE. Some write in notepad, some write in github web interface.

**Comment by basnijholt** [comment]
It definitely will not break anything. They might see a merge conflict, but looking at the PRs, that will probably not happen. Anyway, solving them is nearly trivial. If they’re having problems, I can post the command to fix it or I can make a pull request to their pull request 😄

**Comment by AlexxIT** [comment]
Thanks! Let's see how it works. If it's causing problems, I'll disable the pre-commits :)

**Pull request merged**
