### PR TITLE
Set force_update for sensors to fix issues when value does not change

### PR DESCRIPTION
**Pull request by rany2**
For example,

- Riemann Sum integral integration does not register change if power value was the same. It needs some attribute change. This also breaks that sensor if it went from "unavailable" to a known constant value.

- Graphs don't make as much sense.

### CODE REVIEW

**Comment by AlexxIT** [comment]
And how force update should help with this problem?

**Comment by rany2** [comment]
@AlexxIT Force update will fix this problem because it will trigger an event causing Reimann Sum integration sensor to update. For example, if a sensor went offline and back online but it was off (i.e. power is 0W) -- the energy sensor will remain "unavailable" because the Reimann Sum sensor will only update when this occurs:

- unavailable -> 0W (no update, from invalid previous state to valid current state)
- 0W -> 0W (update because from valid previous state to valid current state)

With force_update, every time a new value is received the last updated attribute will be updated which is what we want here. Currently it assumed that as long as the value doesn't change, the last updated attribute should remain the same because the reading itself didn't change. This is prevents the triggering of another event that will properly update the Reimann Sum sensor when the source sensor attribute/value didn't change.

**Comment by rany2** [comment]
Above is concerning the first point in the [original PR comment](https://github.com/AlexxIT/SonoffLAN/pull/1233#issue-1886305097), if you are asking about "Graphs don't make as much sense" then it's a similar explanation as the above.

Simply it would cause graphing of the power values for example to appear out of place with massive jumps when the power value is consistent. Granted this doesn't happen very often and isn't really annoying but it is enough that it feels a bit strange when you hover over it in ApexCharts. So this isn't as important of an issue to solve for me.

**Comment by AlexxIT** [comment]
Oh. Just setup automation. No need to change source for that
https://github.com/AlexxIT/SonoffLAN#force-update

**Comment by rany2** [comment]
@AlexxIT I already tried it, that doesn't work. No attributes change because the value read is the same.

**Comment by AlexxIT** [comment]
OK. I need to do some tests to check this behavior

**Comment by AlexxIT** [comment]
I don't think this is good idea to set force_update for all sensors. In any way, this makes no sense unless the sensor value is regularly queried...

**Comment by rany2** [comment]
AFAIK, force update will update the "last updated" time every time the sensor value is updated by SonoffLAN (i.e. when calling `homeassistant.update_entity`) even if the sensor value itself didn't change. I'm not sure why this isn't reasonable?

**Comment by AlexxIT** [comment]
Force update will cause the database to grow, whether the user needs it or not. On all sensors in general.
And if the user doesn't use `homeassistant.update_entity`, this growth will be completely useless. Because data saving will be at random points in time.

**Comment by AlexxIT** [comment]
I understand that the "Riemann Sum" needs regular update_entry and force update. But this solution is not an option.

**Comment by rany2** [comment]
I wonder if there is another way to let "Riemann Sum" know that the sensor data is up-to-date. The issue is that the "last updated" time is wrong and it needs an accurate last updated time to be able to properly calculate the energy consumption between the two different data points.

**Comment by rany2** [comment]
I'll close this PR for now, if I find an alternative workaround I'll let you know.

**Comment by AlexxIT** [comment]
As I know, users use python script for this. With regular call and change any sensor attribute.

**Comment by rany2** [comment]
Thanks a lot for the tip, I didn't know that was possible. I'll just make a script that updates that attribute for that specific power sensor I need.

**Comment by rany2** [comment]
This seems to work:

```
rany-msi% cat force_update_entity.py 
entity_id = data.get("entity_id")
c = hass.states.get(entity_id)
hass.states.set(
	entity_id,
	new_state=c.state,
	attributes=c.attributes,
	force_update=True,
	context=c.context,
)
```

I'm not sure if there is a better solution, but it seems like there might not be as the `python_scripts` feature of Home Assistant is insanely restrictive. They disabled all builtins...

**Comment by AlexxIT** [comment]
Check this
https://github.com/AlexxIT/PythonScriptsPro

**Comment by rany2** [comment]
holy shit, thanks man... this is just what I wanted! You have no idea how much time I was wasting trying to workaround the stupid restrictions; if only you told me sooner :D

**Comment by rany2** [comment]
FYI just a miniupdate, but in the latest version of Home Assistant this isn't needed anymore.

**Pull request closed without merging**
