### PR TITLE
Update ru.json

### PR DESCRIPTION
**Pull request by a1ex-ak**
updating the Russian translation

### CODE REVIEW

**Comment by AlexxIT** [comment]
The meaning of the translation has been changed

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN#homes

**Comment by a1ex-ak** [comment]
> https://github.com/AlexxIT/SonoffLAN#homes

Исходя из логики, что Вы описали
Фраза "Дома (оставьте невыбранными для "текущего" дома)" - вводит в заблуждение, тогда нужно перевести на русский так:
"Дома (оставте невыбранным, если у Вас только "текущий" дом)"

**Comment by a1ex-ak** [comment]
Я попроавил текст

**Comment by AlexxIT** [comment]
It doesn't matter how many houses the user has. One or many. One of them will always be the current one.

You problem, that your current home for some reason not your main in the ewelink app. Any way it was your manual choice.

**Comment by AlexxIT** [comment]
I know it's confusing. But it is not my decision. This is how ewelink API works.

**Comment by a1ex-ak** [comment]
> Не имеет значения, сколько домов у пользователя. Один или несколько. Один из них всегда будет текущим.
> 
> У вас проблема с тем, что ваш текущий дом по каким-то причинам не является основным в приложении ewelink. В любом случае это был ваш выбор вручную.

I did not select anything manually and there is no option to select the current house in the application.
I went into the app and checked.

**Comment by a1ex-ak** [comment]
> I know it's confusing. But it is not my decision. This is how ewelink API works.

I corrected the translation as it should be according to the idea of the eWeLink API.
Will you not accept changes?

**Comment by a1ex-ak** [comment]
I closed PR. Sorry

**Comment by AlexxIT** [comment]
Current home selecting in the application in top right corner.

**Comment by a1ex-ak** [comment]
> Current home selecting in the application in top left corner.

True, but this is not a 100% guarantee that it will be automatically selected in the integration.
Sorry for disturbing you. Do I understand correctly that my changes are not needed?

**Comment by a1ex-ak** [comment]
Once again I did the work and corrected it according to your comments. The meaning has not changed compared to yours, but it sounds correct in Russian, and not like a machine translation!

**Comment by AlexxIT** [comment]
Once again. If you not check any checkbox in the integration (by default) it will load devices from current home from top left corner of the app.

**Comment by a1ex-ak** [comment]
> Once again. If you not check any checkbox in the integration (by default) it will load devices from current home (from top left corner of the app).
> 
> Integration won't check any checkbox automatically.
> 
> Text from your changes is not true. I can't accept them.

Вы точно смотрели мои последние правки?

Are you sure you looked at my latest edits?

**Comment by AlexxIT** [comment]
Да, смотрел. Это сообщение неверно: `Дома (оставте невыбранным, если у Вас только \"текущий\" Дом)`

Если у пользователя несколько домов, он всё ещё может оставить пункты невыбранными. Главное, чтоб "текущий" дом его устраивал.

**Pull request closed without merging**
