### PR TITLE
Add support for TH Elite. Fixes #876.

### LINKED ISSUE #876: Sonoff TH elite THR320D or THR316D Sensors
Hello 

I tested the device, is discovered and for now the only entitys available are the relay/Switch, LED and RSSI 

Can you please make the new device from Sonoff Sonoff TH elite THR320D or THR316D also reade and report the information about the sensors connected ? 

The Sensors available are the Temperature, humidity and also the Soil Moisture Sensor

Please let me know if you need any further information in order to get this implemented

Thank you for your work and best regards

### PR DESCRIPTION
**Pull request by jeffallen**
Signed-off-by: Jeff Allen <jallen@pieaeronefs.ch>

### CODE REVIEW

**Comment by CyrielRct** [comment]
Worked for me !

**Comment by AlexxIT** [comment]
Thanks!

**Comment by yingyann** [comment]
Hello, sorry but I’m new on this and what should I do to get it work please? Thank you :-)

**Comment by AlexxIT** [comment]
Fix is included in the latest release https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.1.0

**Pull request merged**
