### PR TITLE
Use imported functions from system_info directly to fix error on 2024.5

### LINKED ISSUE #1405: Update to new core on Home Assistant 2024.5.0 created a new issue
Core 2024.5.0
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.0

Changes made in Home Assistant update today created this new issue:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 4:57:07 PM (3 occurrences)
Last logged: 4:57:18 PM

Detected that custom integration 'sonoff' accesses hass.helpers.system_info. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from system_info directly at custom_components/sonoff/system_health.py, line 61: info = await hass.helpers.system_info.async_get_system_info(), please create a bug report at https://github.com/AlexxIT/SonoffLAN/issues

### PR DESCRIPTION
**Pull request by hmmbob**
Fixes #1405

### CODE REVIEW

**Comment by apardillos** [comment]
It´s works. 2024.5.5 updated OK.

**Comment by lordwizzard** [comment]
@hmmbob and @AlexxIT so when will this be ready. Or how do I get and replace the file with the patch?

**Comment by lordwizzard** [comment]
For those who need to address this:

Go into your HA, find HACS in the left menu, click on it. Find the Sonoff package, click on the 3 dots in the upper right for the package and "redownload". You will be prompted to restart with a notification in the left menu. Restart HA and that should clear the issue.

YMMV due to other changed in the HA cores updated following after the date this was first reported.

Thanks to @hmmbob for his efforst on this issue!

**Comment by AlexxIT** [comment]
Thanks! Did the same thing. And then I saw your PR.

**Pull request closed without merging**
