### PR TITLE
Updated key name in dictionary to match device dict key name

### PR DESCRIPTION
**Pull request by crazyfacka**
With this change, we're now able to see the changes on the UI from using the physical switches plugged to the Dual R3.
I haven't changed the tests, as I am not completely sure if it would be impacting other places in the code.

### CODE REVIEW

**Comment by AlexxIT** [comment]
As I can see [logs here](https://bytemeta.vip/repo/bwp91/homebridge-ewelink/issues/274) - `currLocation` for read position, `location` for write position.

Maybe something have changed in new device firmwares. Have you collect debug logs?

**Comment by crazyfacka** [comment]
When I use the manual wall switches on my Dual R3, I get one line once the motion stops (consistent with the behaviour on the eWeLink app). But only with the change proposed here, I get to see the Home Assistant UI updated with the new final position.

`2022-07-31 17:33:00 [D] 1001436ec2 <= Cloud3 | {'motorTurn': 0, 'currLocation': 82, 'location': 82} | None`

I cannot use them locally in this 3.x version. When in this mode, I know they update live (as seen in 2.x version and eWeLink app).

Thoughts?

I can try and debug further into the code, if you'd like.

**Comment by crazyfacka** [comment]
Just to add that with the latest updates from HA, I am now unable to reach the debug page for the tool. Any other way to reach there @AlexxIT ? Thanks!

**Comment by AlexxIT** [comment]
Yes. Link is broken. Haven't tried to fix it yet.

**Comment by crazyfacka** [comment]
Further debugging, appears that if using "cloud" mode, everything works. Need to debug further when using "local". Closing this. Thanks for the support @AlexxIT .

**Comment by AlexxIT** [comment]
Ok. Thanks for debugging :)

**Pull request closed without merging**
