### PR TITLE
Add support for the Sonoff IW101

### PR DESCRIPTION
**Pull request by mderubertis**
This PR adds support for the [Sonoff IW101](https://www.amazon.ca/gp/product/B081JM45ZZ/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1)

The IW101 has power monitoring and the IW100 does not. Support for the 100 can be added I
 just don't have one so I do not know the uiid.

### CODE REVIEW

**Comment by AlexxIT** [comment]
Hi. Everything should work without your code. Doesn't it work?

**Comment by mderubertis** [comment]
It does work, just found it to misleading since it's primary use is a light switch

**Comment by AlexxIT** [comment]
Sonoff POW has `uiid = 32`. Can't set it as light.

https://github.com/AlexxIT/SonoffLAN/releases/tag/v2.2.3

**Comment by mderubertis** [comment]
The IW101 must be a POW with a different face. Will use my repo instead. Thanks.

**Comment by AlexxIT** [comment]
You can change `device_class` for any device:
https://github.com/AlexxIT/SonoffLAN#custom-device_class-for-any-mode

**Pull request merged**
