### PR TITLE
Fix login failures

### LINKED ISSUE #879: Can't login "sign verification failed"
Hello, 

Since this morning, I can no able longer connect in to my account anymore. See home assistant errors:
image

But I can still use the mobile app with same username/password.

Do you have any idea of what's going on ?

Thanks in advance,

Best regards,

### PR DESCRIPTION
**Pull request by bdraco**
Fixes #879

### CODE REVIEW

**Comment by warthog9** [comment]
Confirmed this sorted the problem for me

**Comment by hmmbob** [comment]
Same here: fixed

**Comment by Santanachia** [comment]
Same here: fixed

**Comment by pimw1** [comment]
The fix works here.

**Comment by hmmbob** [comment]
@AlexxIT Hi Alex, a friendly ping to get this on your radar, if it wasn't yet. Reason for the ping is that after tomorrow (HA release day), a lot more users will be on 2022.7 and will be affected by the issue fixed with this PR.

**Comment by hmmbob** [comment]
Nah, either make [these changes](https://github.com/AlexxIT/SonoffLAN/pull/881/files) directly in `custom_components/sonoff/core/ewelink/cloud.py`.

or go the easy way, [download the complete changed file](https://raw.githubusercontent.com/AlexxIT/SonoffLAN/8182a153312a35f57800f18d8472806c97e02aa9/custom_components/sonoff/core/ewelink/cloud.py) and replace the contents of `custom_components/sonoff/core/ewelink/cloud.py` with it.

**Comment by mupsje** [comment]
hi, also after fix change the cloud.py
Getting a message "appid is unauthorized!  ..............code............................"

greets

**Comment by mupsje** [comment]
Thanks!
Up and Runing again

**Comment by hadadil** [comment]
on my HA only working for few minutes after that all the devices are unavailable 😢

**Comment by swiergot** [comment]
Hmm I have applied the changes but I still get "sign verification failed". Any ideas why?

**Review by pitylee — APPROVED** [review]

**Review by Taldir — APPROVED** [review]

**Comment by hmmbob** [comment]
> > Hmm I have applied the changes but I still get "sign verification failed". Any ideas why?
> 
> Same here after HA Upgrade 2022.7.0

Did you restart HA?

**Comment by swiergot** [comment]
Ok, I know why it didn't work for me. I was still at 2022.06 which apparently is incompatible with the fix.

**Comment by PuschRo** [comment]
> > > Hmm I have applied the changes but I still get "sign verification failed". Any ideas why?
> > 
> > 
> > Same here after HA Upgrade 2022.7.0
> 
> Did you restart HA?

sure :-)  several times

**Comment by thorrrr** [comment]
Same issue i replaced file restarted about 5 times still got same error.
Asks me to re login
https://i.imgur.com/R0Ys239.png
But when i do it says i am already logged in.
https://i.imgur.com/DuzBS2H.png
I have treid auto , cloud and local but none work i have it set to LAN in my app. I have always had it set like that.
https://i.imgur.com/DuzBS2H.png

**Comment by Doktor-X** [comment]
> Same issue i replaced file restarted about 5 times still got same error. Asks me to re login https://i.imgur.com/R0Ys239.png But when i do it says i am already logged in. https://i.imgur.com/DuzBS2H.png I have treid auto , cloud and local but none work i have it set to LAN in my app. I have always had it set like that. https://i.imgur.com/DuzBS2H.png

You need to change 0 to 1 in line 107 and 159

**Comment by PuschRo** [comment]
> > Same issue i replaced file restarted about 5 times still got same error. Asks me to re login https://i.imgur.com/R0Ys239.png But when i do it says i am already logged in. https://i.imgur.com/DuzBS2H.png I have treid auto , cloud and local but none work i have it set to LAN in my app. I have always had it set like that. https://i.imgur.com/DuzBS2H.png
> 
> You need to change 0 to 1 in line 107 and 159

already done, but no success

**Comment by AlexxIT** [comment]
Thanks!

**Comment by Santanachia** [comment]
@AlexxIT Please change the version number so HACS can see that we need to update.

**Comment by armandusbasson** [comment]
> Nah, either make [these changes](https://github.com/AlexxIT/SonoffLAN/pull/881/files) directly in `custom_components/sonoff/core/ewelink/cloud.py`.
> 
> or go the easy way, [download the complete changed file](https://raw.githubusercontent.com/AlexxIT/SonoffLAN/8182a153312a35f57800f18d8472806c97e02aa9/custom_components/sonoff/core/ewelink/cloud.py) ( <-- right-click, save-as) and replace the contents of `custom_components/sonoff/core/ewelink/cloud.py` with it.

Currently this is working fine for me now.

**Comment by AlexxIT** [comment]
@Santanachia do you think I don't know how to do release? :)

**Comment by Santanachia** [comment]
@AlexxIT I know that you know, but it wasn't in the PR. That's the only reason I mention it.

**Comment by problem9** [comment]
@AlexxIT thanks for fast fix

**Comment by thailanna** [comment]
I have downloaded and replaced cloud.py and changed 0 to 1 in line 107 and 159 and even reverted to version 2022.6.7 and still the same problem. I have all my 34 local devices but my 5 remote devices are off-line. These 5 are on a different network/location.
I am asked to reconfigure Sonoff but it comes back with ‘This account is already configured’ but shows 'Failed to set up: sign verification failed
 [34 devices] and [126 entities]. Hope there is a solution in the pipeline.

**Comment by PuschRo** [comment]
> I have downloaded and replaced cloud.py and changed 0 to 1 in line 107 and 159 and even reverted to version 2022.6.7 and still the same problem. I have all my 34 local devices but my 5 remote devices are off-line. These 5 are on a different network/location. I am asked to reconfigure Sonoff but it comes back with ‘This account is already configured’ but shows 'Failed to set up: sign verification failed [34 devices] and [126 entities]. Hope there is a solution in the pipeline.


the same problem with me

**Comment by avellma** [comment]
Some help here, can someone share with me the general steps to get this problem fixed ?
"Failed to set up: sign verification failed"

Where do I need to go to get the file ? What is the file name ? Where in my setting go to change what for what ???
Thank to any one to be patient and guide the one that do not have the experience to navigate this work-stream.
@hmmbob 
@RBSVader 
@PuschRo 
etc ....

**Comment by avellma** [comment]
Thank you @hmmbob .... that was extremely easy and helpful.
It worked perfect....ya the man !!!!

Thank you.....

This community is awesome ....

**Comment by avellma** [comment]
Thank you @AlexxIT

**Comment by yuckypants** [comment]
Thanks @hmmbob !

**Pull request merged**
