### PR TITLE
Fix TX5 ambient light change to 0 mode. error https://github.com/AlexxIT/SonoffLAN/issues/1247

### PR DESCRIPTION
**Pull request by frborda**
In TX5 the ambient light modes ("lightMode") are between 0 and 7. Mode 0 is one of them.

### CODE REVIEW

**Comment by frborda** [comment]
I have tested it on my TX5

**Comment by AlexxIT** [comment]
And why previous condition don't work?

**Comment by frborda** [comment]
because it had the condition of != "0" then modes 1 to 7 worked, but 0 is also a valid option. The device has 8 modes, 0 to 7. To turn off the ambient light it is not mode 0, it is "lightSwitch" to "off"

**Comment by AlexxIT** [comment]
Thanks!

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.6.0

**Pull request merged**
