### PR TITLE
B02 Filament CCT bulb added (UIID:103)

### PR DESCRIPTION
**Pull request by thomasadelhardt**
New bulb from Sonoff: https://www.itead.cc/sonoff-b02-f-smart-led-filament-bulb.html
I don't have the B02 bulb, but I have a FS-1 bulb which appears to be the same bulb its UIID is also 103

### CODE REVIEW

**Comment by thomasadelhardt** [comment]
I think the code is ready for merging.

**Comment by vastagricsi** [comment]
Hi,
Could you tell me how to get UUID of a certain product?
I would like to check the ID of Sonoff B05-B ligtbulb, may I try to check your branch on my environment.
If this works, we should mention it in the file, I guess.

Thanks.

**Comment by thomasadelhardt** [comment]
Look in "/config/.sonoff.json" file, it is located in the same folder as the "configuration.yaml" file.
Look for the UIID of your Ewelink devices in there, a [JSON formater](https://jsonformatter.curiousconcept.com/#) might help.

Your are welcome to use the code as you see fit.

**Comment by vastagricsi** [comment]
Thanks! Now I see that B05-B has UUID of 104.  If I can make it work, I'll let you know as a pull request.

**Comment by AlexxIT** [comment]
@thomasadelhardt Hi, where you get this info:

```
    #   Model "FS-1" might be 2200k-6500K
    #   Model "B02-F-A60"  is 2200K-6500K
    #   Model "B02-F-ST64" is 1800K-5000K
    #   Model "QMS-2C-CW"  is 2700k-6500K
```

**Comment by thomasadelhardt** [comment]
#   Model "FS-1" might be 2200k-6500K
I got this bulb myself, a sticker on the box say it is 2700K-6500.. But as far as I can tell that isn't true, the warmest color looks warmer than 2700K, so my guess is that it is 2200k, but I might be wrong.

    #   Model "B02-F-A60"  is 2200K-6500K - Specifications found on [here](https://www.itead.cc/sonoff-b02-f-smart-led-filament-bulb.html)
    #   Model "B02-F-ST64" is 1800K- - Specifications found on [here](https://www.itead.cc/sonoff-b02-f-smart-led-filament-bulb.html)
    #   Model "QMS-2C-CW"  is 2700k-6500K
At this [thread](https://github.com/AlexxIT/SonoffLAN/issues/269) MortenVinding wrote: "Just got a "Smart Cloud QMS-2C-CW" bulb from Aliexpress. Looks to be the same as the Sonoff: [https://www.aliexpress.com/item/1005001340237235.html](https://www.aliexpress.com/item/1005001340237235.html)" The bulbs specifications it mentioned at the Aliexpress page.

**Comment by AlexxIT** [comment]
@thomasadelhardt ok, I merged your code in latest beta. But change it a little

**Comment by marianobntz** [comment]
It is not working for B02 model, I get this message when starting HA.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 315, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 421, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/config/custom_components/sonoff/light.py", line 608, in capability_attributes
    ATTR_MIN_MIREDS: round(self._min_mireds),
TypeError: type NoneType doesn't define __round__ method

**Comment by marianobntz** [comment]
I have the config/.sonoff.json, what information do you need from there?

**Pull request merged**
