### PR TITLE
Dual R3 Measured Values

### LINKED ISSUE #482: Sonoff Dual R3 can't display "power,voltage,current" state
because keyword not "power,voltage,current"

it's:
 
"current_00":1,"voltage_00":23118,"actPow_00":160,"reactPow_00":262,"apparentPow_00":308,"
"current_01":0,"voltage_01":23004,"actPow_01":0,"reactPow_01":0,"apparentPow_01":0

### PR DESCRIPTION
**Pull request by seppelw**
This ads support to read the measured values from a Dual R3 and convert them to float, to be used as sensors.
This (partially) fixes #482 
cheers!

### CODE REVIEW

**Comment by seppelw** [comment]
@AlexxIT what do you think about this?

**Comment by AlexxIT** [comment]
I think it should be rewriten. Not best name of attributes and not best place with processing it.
I will do it when have a time. Thanks!

**Comment by shummo** [comment]
HI. Can you, seppelw help  me pls.
I rewrite the sonoff_main.py and the sensor.py.
Now i didn't find the hacs.json.

Can you tell me please, what i have to do with your codes, to see the Measured Values of the Dualr3 in METER/SWITCH working  mode?

Thanks

**Comment by AlexxIT** [comment]
Why you don't have `current_01` and etc. in you logs?

**Comment by shummo** [comment]
> Why you don't have `current_01` and etc. in you logs?

Because I only use now the 00 channel.  The second switch/port is still not in use.

**Comment by Gagge89** [comment]
Hello everyone, I use Sonoff on Home Assistant and I all have Sonoff Dual R3 .. I did not understand however how I can view the consumption (current, voltage and power) of each of the 2 outputs as I can see on Ewelink Web or on the Ewelink app . How can I do? Thank you

**Pull request closed without merging**
