### PR TITLE
Switch to async zeroconf / AsyncServiceBrowser

### LINKED ISSUE #622: Consider switching to AsyncZeroconf
It looks like you might be able to save some jumps between sync and async context now that zeroconf is async under the hood.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/zeroconf/__init__.py#L99

### PR DESCRIPTION
**Pull request by bdraco**
- Fix a sleep in the sensor platform that was blocking
  the event loop and causing instability

Closes #622

### CODE REVIEW

**Comment by chemelli74** [comment]
@AlexxIT do you mind checking this PR ? 
Thank you in advance,

Simone

**Comment by AlexxIT** [comment]
@chemelli74 I am developing a new version of the component with completely redesigned code.

**Comment by bdraco** [comment]
superseded by https://github.com/AlexxIT/SonoffLAN/issues/751

**Comment by AlexxIT** [comment]
@bdraco Your version of zeroconf no longer generates `ServiceStateChange.Removed` events. I checked history. 
v0.31.0 was latest version with support this event :(

**Comment by bdraco** [comment]
@AlexxIT Its definitely still supported and just verified we are fixing them with a homekit device.


https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_services/browser.py#L343
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_services/__init__.py#L38
https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_services/__init__.py#L34

Feel free to message me on Home Assistant discord as bdraco#6479 if you need some help with it.

**Comment by bdraco** [comment]
Can you try testing with https://github.com/jstasiak/python-zeroconf/blob/master/examples/async_browser.py? You'll need to adjust the type here https://github.com/jstasiak/python-zeroconf/blob/master/examples/async_browser.py#L56



Service HASS Bridge 07CEEE._hap._tcp.local. of type _hap._tcp.local. state changed: ServiceStateChange.Removed

**Pull request closed without merging**
