### PR TITLE
Add optional port parameter for devices

### PR DESCRIPTION
**Pull request by GenkaOk**
Port can be changed by port mapping in router.

### CODE REVIEW

**Comment by AlexxIT** [comment]
Oh. I think devise sends its port over zeroconf. Can you check with some utility? Like this one:
https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12

**Comment by GenkaOk** [comment]
> Oh. I think device sends its port over zeroconf. Can you check with some utility? Like this one:
> https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12

Yes, device send. But this option need for port mapping between networks.

HA in 1 network - 192.168.0.1
Sonoff x2 in 2 network - 192.168.1.1:8081, 192.168.1.1:8082 (192.168.0.2:8081 -> 8081, 192.168.0.3:8081 -> 8082)

**Comment by AlexxIT** [comment]
You have installed some mDNS proxy between networks? Don't understand your config.

**Comment by GenkaOk** [comment]
No, it's request for manual configuration.
Without mDNS.

**Comment by AlexxIT** [comment]
Ok. You can add host:port (single field) to YAML from latest release
https://github.com/AlexxIT/SonoffLAN/blob/941cbb3a10b9e486368d7f9b0d9fb41c2ced32b9/custom_components/sonoff/core/ewelink/__init__.py#L42-L43

**Pull request closed without merging**
